version: '3'
services:
  aicam:
    image: aicam
    container_name: aicam
    environment:
      - MODELDIR=/models/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
      - STREAMURL=http://192.168.1.1:8080/video
    command: bash -c "while true; do sleep 3600; done"
    volumes:
      - .:/aicam
      - ./recordings:/recordings
