version: '3'
services:
  aicam_sw:
    image: aicam
    container_name: aicam_sw
    command: python aicam.py --modeldir ${MODELDIR} --streamurl ${STREAMURL_SW} --resolution 640x480 --mqtt_host=${MQTT_HOST} --mqtt_name sw --threshold 0.65
    volumes:
      - .:/aicam
      - ./recordings:/recordings
  aicam_se:
    image: aicam
    container_name: aicam_se
    command: python aicam.py --modeldir ${MODELDIR} --streamurl ${STREAMURL_SE} --resolution 640x480 --mqtt_host=${MQTT_HOST} --mqtt_name se --threshold 0.65
    volumes:
      - .:/aicam
      - ./recordings:/recordings

# Create a .env file with the following variables
# set the user, password and ip address of your cameras
# Alternatively set the environment variables before running docker-compose
# Run with docker-compose up -d

# MODELDIR=/models/ssdlite_mobiledet_cpu_320x320_coco_2020_05_19/
# STREAMURL_SW=rtsp://user:passwd@192.168.1.240:554//h264Preview_01_sub
# STREAMURL_SE=rtsp://user:passwd@192.168.1.241:554//h264Preview_01_sub
# MQTT_HOST=192.168.1.42
