[tool.ruff]
fix = true
select = ["F", "E", "C90", "I", "N", "D", "UP", "YTT", "ANN", "S", "BLE", "FBT", "B", "A", "COM", "C4", "DTZ", "T10", "DJ", "EM", "EXE", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY", "NPY", "RUF"]
ignore = ["A003",    # Class attribute shadowing builtins. Affects next, set, type
          "ANN002",  # *args annotation
          "ANN003",  # **kwargs annotation
          "ANN101",  # Missing type annotations for self in a class method
          "ANN204",  # Missing return type annotation for magic method
          "COM812",  # Missing comma after last item
          "D105",    # Missing docstring in magic method
          "D107",    # Missing docstring in __init__
          "E501",    # Line too long
          "S101"]    # Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
